# Generated by Django 5.1 on 2024-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeshop',
            name='clientes',
        ),
        migrations.AddField(
            model_name='coffeshop',
            name='clientes',
            field=models.ManyToManyField(to='shop.client'),
        ),
    ]
