# Generated by Django 5.1 on 2024-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_coffeshop_clientes_coffeshop_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeshop',
            name='clientes',
        ),
        migrations.AddField(
            model_name='client',
            name='clientes',
            field=models.ManyToManyField(to='shop.coffeshop'),
        ),
    ]
