# Generated by Django 5.1 on 2024-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_coffeshop_clientes_client_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeshop',
            name='productos',
        ),
        migrations.AddField(
            model_name='coffeshop',
            name='productos',
            field=models.ManyToManyField(to='shop.products'),
        ),
    ]
