# Generated by Django 5.1 on 2024-08-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_coffeshop_productos_coffeshop_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientes',
        ),
        migrations.AddField(
            model_name='coffeshop',
            name='client',
            field=models.ManyToManyField(to='shop.client'),
        ),
    ]
