# Generated by Django 5.1 on 2024-08-12 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_client_clientes_coffeshop_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeshop',
            old_name='client',
            new_name='clientes',
        ),
        migrations.AlterField(
            model_name='products',
            name='cant',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_id', message='La cantidad solo puede contener números.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='cod_product',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_id', message='El ID del prodcuto solo puede contener números.', regex='^[0-9]*$')]),
        ),
    ]
